export const MOBILE_INPUT_CONFIG = {
  movementSideRatio: 0.5,
  aimSideStartRatio: 0.5,
  bottomControlStartRatio: 0.36,
  compactScreenMax: 760,
  tabletMinShortSide: 900,
  joystickDeadZone: 0.12,
  joystickDeadZoneShape: 'radial',
  aimDeadZone: 0.16,
  aimDeadZoneShape: 'radial',
  aimReleaseFireDeadZone: 0.22,
  joystickReleaseLerp: 0.28,
  joystickFollowLerp: 0.58,
  joystickVisibleLerp: 0.34,
  joystickFadeLerp: 0.16,
  joystickActivationDecay: 0.08,
  joystickMaxTravelFactor: 0.12,
  joystickBaseRadiusFactor: 0.105,
  joystickKnobTravelFactor: 0.46,
  aimSensitivity: 0.94,
  aimSmoothing: 0.42,
  aimRadiusFactor: 0.16,
  aimVelocitySensitivityBoost: 0.12,
  aimVelocitySensitivityMaxSpeed: 12,
  aimAssistEnabled: true,
  aimAssistConeDeg: 24,
  aimAssistInnerConeDeg: 11,
  aimAssistRange: 360,
  aimAssistStrength: 0.36,
  aimAssistMaxStrength: 0.78,
  aimAssistInputThreshold: 0.26,
  aimAssistCurveExponent: 1.4,
  aimIndicatorRange: 360,
  aimIndicatorIdleOpacity: 0.28,
  aimIndicatorActiveOpacity: 0.9,
  attackCooldownVisualFrames: 40,
  attackBufferFrames: 14,
  maxAttackBufferFrames: 48,
  platformDropFrames: 12,
  platformDropVelocity: 8,
  jumpSwipeDistance: 56,
  dropSwipeDistance: 66,
  swipeDirectionBias: 1.24,
  tapMaxDurationMs: 180,
  tapMaxTravel: 28,
  doubleTapWindowMs: 240,
  doubleTapMaxDistance: 82,
  swapLongPressMs: 340,
  radialMenuDeadZoneFactor: 0.72,
  radialMenuOuterFactor: 3.4,
  buttonHitSlop: 1.55,
  actionButtonRadiusFactor: 0.074,
  secondaryButtonRadiusFactor: 0.058,
  actionButtonGapFactor: 1.08,
  tabletSpreadFactor: 1.08,
  compactSpreadFactor: 0.92,
  safeMarginFactor: 0.03,
} as const;

export const MOBILE_CONTROL_ASSET_PATHS = {
  joystickBase: '/assets/mobile-controls/joystick-base.svg',
  joystickKnob: '/assets/mobile-controls/joystick-knob.svg',
  shoot: '/assets/mobile-controls/shoot.svg',
  dash: '/assets/mobile-controls/dash.svg',
  jump: '/assets/mobile-controls/jump.svg',
  pause: '/assets/mobile-controls/pause.svg',
  cycle: '/assets/mobile-controls/cycle.svg',
  crosshair: '/assets/mobile-controls/crosshair.svg',
  abilitySlot: '/assets/mobile-controls/ability-slot.svg',
} as const;

export type MobileControlAssetKey = keyof typeof MOBILE_CONTROL_ASSET_PATHS;
